### PR TITLE
JZ - fix tests

### PR DESCRIPTION
**Pull request by Jameszhao1103**

### CODE REVIEW

**Comment by Jameszhao1103** [comment]
Mutation test passed

**Comment by tallyhawley** [comment]
i deployed this to the QA heroku and i saw that you're having the same error that ethan was having: 
image

@ethanlee556 how did you solve this?

**Comment by ethanlee556** [comment]
> i deployed this to the QA heroku and i saw that you're having the same error that ethan was having: image
> 
> @ethanlee556 how did you solve this?

For me the api path was not the same as the one i used in team02

**Comment by Jameszhao1103** [comment]
> i deployed this to the QA heroku and i saw that you're having the same error that ethan was having: image
> 
> @ethanlee556 how did you solve this?

OK I changed the API to match what I have in team02. Can you run again to see if everything is fine?

**Review by liamjet — APPROVED** [review]
LGTM.

**Pull request merged**
